# Generated by Django 4.2.5 on 2023-09-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
